# Create a namespace for Argo CD
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: argo-cd-namespace
manifests:
  kustomize:
    paths:
      - gitops-argo-cd/namespace
deploy:
  kubectl: {}
---
# Deploy an Argo CD instance
apiVersion: skaffold/v4beta13
kind: Config
requires:
  - configs:
      - argo-cd-namespace
metadata:
  name: argo-cd-instance
manifests:
  helm:
    releases:
      - name: argo-cd
        namespace: argocd
        remoteChart: argo-cd
        repo: https://argoproj.github.io/argo-helm
        upgradeOnChange: true
        valuesFiles:
          - gitops-argo-cd/instance/values.yaml
        version: 9.4.0
deploy:
  helm: {}
---
# Get Argo CD to pick up all personal-apps resources.
apiVersion: skaffold/v4beta13
kind: Config
requires:
  - configs:
      - argo-cd-namespace
      - argo-cd-instance
metadata:
  name: bootstrap-parent-app
manifests:
  kustomize:
    paths:
      - gitops-argo-cd/bootstrap-parent-app
deploy:
  kubectl: {}
