apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Harmelodic/personal-apps.git
    targetRevision: HEAD
    path: applications/argo-cd-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
