apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.2
    helm:
      releaseName: cert-manager
      valuesObject:
        extraArgs:
          - "--issuer-ambient-credentials=true" # Needed for Workload Identity for Cloud DNS solving
        installCRDs: true
        serviceAccount: # Service Account is created elsewhere for Workload Identity
          create: false
          name: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
