apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.8.2
    helm:
      releaseName: cert-manager
      parameters:
        - name: installCRDs
          value: "true"
        - name: serviceAccount.create
          value: "false"
        - name: serviceAccount.name
          value: "cert-manager"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
