apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.12.2
    helm:
      releaseName: cert-manager
      parameters:
        - name: installCRDs
          value: "true"
        - name: serviceAccount.create
          value: "false" # Needed for setting up Workload Identity on customer cert-manager Service Account
        - name: serviceAccount.name
          value: cert-manager # Needed for setting up Workload Identity on custom cert-manager Service Account
        - name: extraArgs[0]
          value: --issuer-ambient-credentials=true # Needed for Workload Identity for Cloud DNS solving
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
