apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harmelodic-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Harmelodic/personal-apps.git
    targetRevision: HEAD
    path: applications/harmelodic-website/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: harmelodic
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
