apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: broker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: broker
    spec:
      serviceAccountName: broker
      containers:
        - name: broker
          image: pactfoundation/pact-broker:2.105.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9292
              name: http
          env:
            - name: PACT_BROKER_BASE_URL
              value: https://pact.harmelodic.com:443
            - name: PACT_BROKER_DATABASE_ADAPTER
              value: postgres
            - name: PACT_BROKER_DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: username
                  name: broker-database-connection # Created by Database IaC
            - name: PACT_BROKER_DATABASE_PASSWORD
              value: ""
            - name: PACT_BROKER_DATABASE_HOST
              value: localhost
            - name: PACT_BROKER_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: database
                  name: broker-database-connection # Created by Database IaC
            - name: PACT_BROKER_DATABASE_PORT
              value: "5432"
            - name: PACT_BROKER_ALLOW_PUBLIC_READ
              value: "true"
#            - name: PACT_BROKER_BASIC_AUTH_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  key: username
#                  name: broker-auth
#            - name: PACT_BROKER_BASIC_AUTH_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  key: password
#                  name: broker-auth
            - name: PACT_BROKER_PUBLIC_HEARTBEAT
              value: "true"
            - name: PACT_BROKER_LOG_LEVEL
              value: ERROR
#          resources:
#            requests:
#              cpu: 100m
#              memory: 100Mi
#            limits:
#              cpu: 200m
#              memory: 200Mi
          startupProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /diagnostic/status/heartbeat
              port: http
          readinessProbe:
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /diagnostic/status/heartbeat
              port: http
          livenessProbe:
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /diagnostic/status/heartbeat
              port: http
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.31.2-alpine
          command:
            - /cloud_sql_proxy
            - -ip_address_types=PRIVATE
            - -log_debug_stdout
            - -enable_iam_login
            - -instances=$(INSTANCE_CONNECTION_NAME)=tcp:5432
          env:
            - name: INSTANCE_CONNECTION_NAME
              valueFrom:
                configMapKeyRef:
                  key: instance-connection-name
                  name: broker-database-connection # Created by Database IaC
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
