apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: pact-broker
  app.kubernetes.io/created-by: harmelodic
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: pact-broker
  app.kubernetes.io/part-of: pact-broker
  app.kubernetes.io/version: latest
resources:
  - deployment.yaml
  - ingress.yaml
  - issuer.yaml
  - service.yaml
