apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: broker
  app.kubernetes.io/part-of: broker
resources:
  - deployment.yaml
  - ingress.yaml
  - issuer.yaml
  - service.yaml
