apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: blog
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blog
    spec:
      serviceAccountName: blog
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: blog
          image: europe-north1-docker.pkg.dev/personal-artifacts-353012/harmelodic/blog:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: management-http
              containerPort: 8081
          env:
            - name: CONTENTFUL_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: base-url
                  name: contentful
            - name: CONTENTFUL_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: environment
                  name: contentful
            - name: CONTENTFUL_SPACE
              valueFrom:
                configMapKeyRef:
                  key: space
                  name: contentful
            - name: CONTENTFUL_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: contentful
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 250Mi
          startupProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /actuator/health/liveness
              port: management-http
          readinessProbe:
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /actuator/health/readiness
              port: management-http
          livenessProbe:
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /actuator/health/liveness
              port: management-http
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false # Spring wants to create temp directories
            capabilities:
              drop:
                - ALL
